[build]
command = "npm install && npm run build"  # Change according to your setup
publish = "client/build"  # Path to frontend build folder

[functions]
directory = "functions"  # Serverless functions folder

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
